### ISSUE TITLE
表格可编辑的时候，表头计算有问题

### ISSUE THREAD

**Issue by curryz** [YongTay/auto-column#2]
在表格进入可编辑的时候，单元格展示的是input或者select，表头在重新计算的时候，会出现宽度较小
感谢回复，respect！！！

**Comment by YongTay** [comment]
感谢你的反馈，可以尝试更新到最新版本

**Comment by curryz** [comment]
<img width="251" alt="image" src="https://github.com/YongTay/auto-column/assets/22360636/143b0867-f951-4cec-8f15-87994ad3cd4d">
貌似新版有点问题，可编辑的时候没有问题，就是表头的宽好像都均分了

**Comment by YongTay** [comment]
你提到的问题未曾复现。
请提供vue相关版本信息，最新版本解决一些在vue不同版本下可能出现的已知错误

**Comment by curryz** [comment]
版本是："vue": "^2.6.14", "element-ui": "^2.15.8",

**Comment by curryz** [comment]
是我代码的原因。。。。
