### ISSUE TITLE
表格里面数据为空，表头会平均分

### ISSUE THREAD

**Issue by curryz** [YongTay/auto-column#3]
如果表格里面数据为空，表头会平均分宽，看着不是根据表格的宽度来的

**Comment by YongTay** [comment]
不明白你的问题在哪，如果表格宽度不合适可以查看文档使用全局参数进行最小宽度配置。
或者可以尝试clone项目，提交代码，审查过后会被合并到下个版本。

**Comment by curryz** [comment]
复杂的情况不适合，比如说表头100个字，内容是一个两位数，与表头两个字，内容100个字的，这种适配的感觉不是特别好
